export { RegistrationViewModel } from './models/registration-view-model';
export { ApplicantViewModel } from './models/applicant-view-model';
export { Application } from './models/application';
export { ResidentialAddress } from './models/residential-address';
export { AlternativePerson } from './models/alternative-person';
export { PostalAddress } from './models/postal-address';
export { AlternativeAddress } from './models/alternative-address';
export { CredentialsViewModel } from './models/credentials-view-model';
export { FacebookAuthViewModel } from './models/facebook-auth-view-model';
